### ISSUE TITLE
Automate latest version

### ISSUE THREAD

**Issue by Wintus** [Wintus/ansible-role-go-tools#4]
https://github.com/Wintus/ansible-role-go-tools/blob/be009798019501838189f87113cd55f5ff6a1146/defaults/main.yml#L4

Use GitHub release module

```yaml
- name: Install annoyingly unpackaged python module requirement
  pip:
    state: latest
    umask: "0022"
    name: github3.py

- name: Find current release tag
  github_release:
    user: github
    repo: hub
    action: latest_release
  register: release_data

- debug:
    var: release_data
- debug:
    var: release_data.tag[1:]
```
